[package]
name = "jun-pre"
version = "0.1.0"
entrypoint = "themes/jun-beamer.typ"
authors = ["JL-ghcoder <isjun.liu@gmail.com>"]
license = "MIT"
description = "Touying Slide Theme for Jun's Pre"
homepage = "https://github.com/JL-ghcoder/Typst-Pre-Template"
repository = "https://github.com/JL-ghcoder/Typst-Pre-Template"
keywords = ["touying", "slide", "theme", "presentation"]
categories = ["presentation"]
exclude = [".github/", "examples/"]

[template]
path = "examples"
entrypoint = "main.typ"
thumbnail = "figures/red.png"